### ISSUE TITLE
Hinzufügen von Bäumen und Dateneingabe

### ISSUE THREAD

**Issue by Kronenwerk** [baumsicht/Baumkataster#7]
Hallo Philipp, ich habe das gleiche Problem wie Florian Wagner
[19. März 2024 um 12:24 Uhr](https://baumsicht.de/dokumentation-baumkataster4/hinzufuegen-von-baeumen-und-dateneingabe/#comment-25972) in der Doku...
Jedes Mal, wenn ich im Digitalisierungsmodus einen neuen Baum über das Feld unten rechts hinzufügen möchte kommt das angehängte Bild und ich muss die App neustarten. Zwar ist der Baumstandort dann digitalisiert, aber dennoch aufwendig, jedes Mal die App neu zu starten..
Gibt es da eine Lösung für ?

Meine Qfieldversion ist: Version 3.2.2 - Congo
Baumkatasterversion ist: Baumkataster 4.1
![Qfield Fehlerbild](https://github.com/baumsicht/Baumkataster/assets/167905899/92d205b3-9248-4310-9b02-e06a1755516b)

**Comment by baumsicht** [comment]
Bitte in QGIS die Registerkarte `Letzte` löschen. Ggf. zwei Projekte für Ersterfassung (ohne diese Registerkarte) und Folgekontrolle (mit Registerkarte `Letzte`) verwenden.

**Comment by baumsicht** [comment]
In der Version 4.5.2 gibt es nun ein Projekt (`baumkataster_projekt_ersterfassung.qgs`) für die Ersterfassung ohne die Registerkarte `Letzte`.
